/** English — the garden's mirror language; taxonomy strings translated here. */
import type { UIStrings } from './types';

export const strings: UIStrings = {
  searchPlaceholder: 'Search the garden… (Esc to close)',
  searchHint: 'Titles, sections and body text, in this language.',
  searchEmpty: 'No note matches.',
  searchUnavailable: 'The search index could not be loaded.',
  searchUnit: 'pages',
  searchScopeAll: 'All',
  searchDialog: 'Site search',
  searchInput: 'Search the garden',
  searchResults: 'Search results',
  searchButton: 'Search (⌘K)',

  languages: 'Language',

  breadcrumb: 'Breadcrumb',
  contents: 'Contents',
  chapterNav: 'Chapter navigation',
  prev: '← prev',
  next: 'next →',
  hub: 'Hub',
  overview: 'Overview',
  updated: 'updated',
  backlinks: 'Linked mentions',
  localGraph: 'Local graph',
  lightbox: 'Image viewer',
  close: 'Close',
  copied: 'Code copied to the clipboard',
  copyFailed: 'Copy failed — the clipboard is not available',
  theme: 'Toggle light / dark theme',
  menu: 'Menu',
  skip: 'Skip to content',
  partLabel: (roman) => `Part ${roman}`,
  readingTime: (min) => `${min} min read`,
  footer: 'Yufeng Hub · a personal garden: notes, papers and a vault',

  landingTitle: 'Yufeng Hub · a personal garden',
  landingDesc: "Yufeng Jin's personal knowledge garden — notes, a paper wall and a private vault.",

  speakLabel: 'In plain words →',
  diffLabel: 'vs prior →',

  kinds: {
    note: { label: 'Note', desc: 'One topic, worked through: concept, mechanism, experiment' },
    paper: { label: 'Paper', desc: 'Close readings and surveys — read, thought through, written down' },
    project: { label: 'Project', desc: 'Hands-on records: builds, experiments, retrospectives' },
    reference: { label: 'Reference', desc: 'Quick lookups and checklists' },
  },
  domains: {
    ml: { label: 'Machine Learning', desc: 'Models, training, generative methods and the intuition behind them' },
    robotics: { label: 'Robotics', desc: 'Embodied AI: manipulation, perception, VLAs and teleoperation' },
    math: { label: 'Mathematics', desc: 'Linear algebra, probability, optimization — math for engineering' },
    programming: { label: 'Programming', desc: 'Languages, systems, toolchains and engineering practice' },
    infra: { label: 'Infrastructure', desc: 'Servers, networking, deployment — everything self-hosted' },
  },
  statuses: {
    seedling: { label: 'Seedling', desc: 'A stub — planted, not yet grown' },
    growing: { label: 'Growing', desc: 'A living document, still being written' },
    evergreen: { label: 'Evergreen', desc: 'Mature and maintained' },
  },

  browse: {
    kicker: 'Garden',
    kickerSub: 'read, thought through, written down',
    title: 'Yufeng Hub',
    titleSub: 'a growing personal knowledge garden',
    lede: (notes, domains) =>
      `Notes, papers and project records, grown as a garden — ${notes} notes across ${domains} domains, browsable by kind, domain and tag`,
    sep: '. Also: ',
    stop: '.',
    papersLink: 'the paper wall',
    legacyLink: 'the legacy learning-notes site',
    recent: 'Recently updated',
    recentSub: 'the last three to change',
    shelfCount: (n) => `${n} primary · all →`,
    allNotes: 'All notes →',
    byKind: 'By kind',
    byDomain: 'By domain',
    byStatus: 'By status',
    byTag: 'By tag',
    facetLede: (desc, n) => `${desc} — ${n} notes.`,
    domainLede: (desc, n) => `${desc} — ${n} notes, primary or secondary.`,
    tagLede: (n) => `${n} notes.`,
    tagDesc: (tag, n) => `Notes tagged ${tag} (${n})`,
    facetDesc: (desc, n) => `${desc} (${n} notes)`,
    all: 'All notes',
    allKicker: 'every last one',
    allEntries: (n) => `${n} notes`,
    allDesc: (n) => `Every note in the garden (${n}), newest first, filterable in place.`,
    allLede: 'Newest first. The filters below narrow in place; without JavaScript they jump to the facet pages.',
    dimKind: 'Kind',
    dimDomain: 'Domain',
    dimStatus: 'Status',
    dimTag: 'Tag',
    facetsAria: 'Browse index',
    facetAll: 'All →',
    clear: 'Clear filters',
    noMatch: 'No note matches every selected filter.',
    allTags: 'All tags',
    chapters: (n) => `${n} chapters`,
  },
};
